from __future__ import annotations

from os import PathLike
from typing import Any, Literal, TypedDict

IsolationLevel = Literal["snapshot", "serializable"]
ExplainMode = Literal["binder", "planner", "optimizer", "physical", "pipelines", "analyze"]

class ColumnInfo(TypedDict):
    name: str
    type: str
    primary_key: bool

class TableInfo(TypedDict):
    name: str
    columns: list[ColumnInfo]
    primary_key: list[str]
    generated_id: bool
    storage: Literal["row", "parquet"]
    location: str | None
    estimated_rows: int

class GarbageCollectionStats(TypedDict):
    timed_out: int
    reclaimed: int

class ResourceStats(TypedDict):
    worker_capacity: int
    active_worker_slots: int
    peak_worker_slots: int
    query_memory_used: int
    query_memory_peak: int
    active_operations: int

__version__: str

class BumbleBeeError(Exception): ...
class DatabaseError(BumbleBeeError): ...
class DatabaseClosedError(DatabaseError): ...
class ParserError(DatabaseError): ...
class BinderError(DatabaseError): ...
class PlannerError(DatabaseError): ...
class ExecutionError(DatabaseError): ...
class ConflictError(ExecutionError): ...
class NotImplementedError(DatabaseError): ...
class ProgrammingError(BumbleBeeError): ...
class DataError(BumbleBeeError): ...

class Result:
    @property
    def columns(self) -> list[str]: ...
    @property
    def types(self) -> list[str]: ...
    @property
    def row_count(self) -> int: ...
    @property
    def is_command(self) -> bool: ...
    @property
    def command_tag(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def affected_rows(self) -> int | None: ...
    def tuples(self) -> list[tuple[Any, ...]]: ...
    def to_df(self) -> Any: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = 1) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Result: ...
    def __next__(self) -> tuple[Any, ...]: ...

class Connection:
    @property
    def closed(self) -> bool: ...
    @property
    def in_transaction(self) -> bool: ...
    def sql(self, query: str) -> Result: ...
    def execute_script(self, script: str) -> list[Result]: ...
    def run_file(self, path: str | PathLike[str]) -> list[Result]: ...
    def begin(self, isolation: IsolationLevel = "snapshot") -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def transaction(self, isolation: IsolationLevel = "snapshot") -> _TransactionContext: ...
    def get_tables(self) -> list[TableInfo]: ...
    def describe_table(self, name: str) -> TableInfo: ...
    def get_table(self, name: str) -> Result: ...
    def remove_table(self, name: str, *, if_exists: bool = False) -> bool: ...
    def vacuum(self, name: str) -> int: ...
    def collect_garbage(self) -> GarbageCollectionStats: ...
    def explain(self, query: str, *, mode: ExplainMode = "physical") -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class _TransactionContext:
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> bool: ...

class Database:
    def __init__(
        self,
        path: str | PathLike[str] | None = None,
        *,
        worker_threads: int = 0,
        max_memory: int | None = None,
        frames: int | None = None,
        morsel_pages: int | None = None,
        transaction_timeout: float | None = None,
        prefer_external: bool = False,
    ) -> None: ...
    @property
    def closed(self) -> bool: ...
    def sql(self, query: str) -> Result: ...
    def connect(self) -> Connection: ...
    def execute_script(self, script: str) -> list[Result]: ...
    def run_file(self, path: str | PathLike[str]) -> list[Result]: ...
    def get_tables(self) -> list[TableInfo]: ...
    def describe_table(self, name: str) -> TableInfo: ...
    def get_table(self, name: str) -> Result: ...
    def remove_table(self, name: str, *, if_exists: bool = False) -> bool: ...
    def vacuum(self, name: str) -> int: ...
    def collect_garbage(self) -> GarbageCollectionStats: ...
    def resource_stats(self) -> ResourceStats: ...
    def explain(self, query: str, *, mode: ExplainMode = "physical") -> str: ...
    def load_df(
        self,
        frame: Any,
        name: str,
        *,
        primary_key: str | list[str] | tuple[str, ...] | None = None,
        if_exists: str = "error",
        include_index: bool = False,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Database: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

def db(
    path: str | PathLike[str] | None = None,
    *,
    worker_threads: int = 0,
    max_memory: int | None = None,
    frames: int | None = None,
    morsel_pages: int | None = None,
    transaction_timeout: float | None = None,
    prefer_external: bool = False,
) -> Database: ...
